name: FarmCart-Caddy

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: ./backend/.env.prod
    networks:
      - app-network-caddy
    # ports:
    #   - "5002:5002"  # Expose the API on port 5002 for internal communication

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod  # This Dockerfile serves React with Caddy
    restart: unless-stopped
    ports:
      - 80:80  # HTTP port
      - 443:443  # HTTPS port for SSL

    depends_on:
      - api
    networks:
      - app-network-caddy

networks:
  app-network-caddy:
    driver: bridge
