services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    environment:
      PORT: 5000
      NODE_ENV: production
      MONGODB_URI: "your_mongodb_uri"
      JWT_SECRET: "your_jwt_secret"
      CLOUDINARY_CLOUD_NAME: "your_cloudinary_cloud_name"
      CLOUDINARY_API_KEY: "your_cloudinary_api_key"
      CLOUDINARY_API_SECRET: "your_cloudinary_api_secret"
      EMAIL_USER: "your_email_user"
      EMAIL_PASS: "your_email_pass"
      EMAIL_SERVICE: "gmail"
      SITE_URL: "http://0.0.0.0:3000"
      PAYHERE_MERCHANT_ID: "your_payhere_merchant_id"
      PAYHERE_MERCHANT_SECRET: "your_payhere_merchant_secret"
      CRYPTO_SECRET_KEY: "your_crypto_secret_key"
      STRIPE_SECRET_KEY: "your_stripe_secret_key"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    environment:
      VITE_API_URL: "http://api:5001/api"
      VITE_STRIPE_PUBLIC_KEY: "Stripe Public Key"
      VITE_HOST: "0.0.0.0"
      VITE_PORT: "3000"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
