name: FarmCart-Caddy

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: ./backend/.env.prod
    networks:
      - app-network-caddy
    deploy:
      mode: replicated
      replicas: 2
    healthcheck:
      test: ["CMD", "curl", "-f", "api:5002/health"]  # Use service name instead of localhost
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    
    # ports:
    #   - "5002:5002"  # Expose the API on port 5002 for internal communication

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod  # This Dockerfile serves React with Caddy
      args:
        - VITE_STRIPE_PUBLIC_KEY=pk_test_51LMEvTC05RrpHY1zUINiBb70Oue9TVmbH9LoKTZKKa0Ra3a8J188Ph3kouCpSeLJUr7qCgndpWlAXwt5GVlZOLIY00SkMj6avh
        - VITE_MAPBOX_API_KEY=pk.eyJ1IjoibGtzbmp3IiwiYSI6ImNtMjA2c3ZkOTBiYWwyaXF2M2lqM2tleTQifQ.DZLGqlXwdK7VmyE1zlpxDg
    restart: unless-stopped
    env_file: ./frontend/.env.prod
    ports:
      - 80:80  # HTTP port
      - 443:443  # HTTPS port for SSL
    volumes:
      - $PWD/frontend/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    networks:
      - app-network-caddy


networks:
  app-network-caddy:
    driver: bridge

volumes:
  caddy_data:
    external: true
  caddy_config:
