const DistrictsData = {
    Ampara: ['Ampara', 'Kalmunai', 'Sainthamaruthu'],
    Anuradhapura: ['Anuradhapura', 'Medawachchiya', 'Kekirawa'],
    Badulla: ['Badulla', 'Bandarawela', 'Haputale'],
    Batticaloa: ['Batticaloa', 'Eravur', 'Valachchenai'],
    Colombo: [
        'Colombo 01',
        'Colombo 02',
        'Colombo 03',
        'Dehiwala',
        'Mount Lavinia',
    ],
    Galle: ['Galle', 'Hikkaduwa', 'Ambalangoda'],
    Gampaha: ['Negombo', 'Gampaha', 'Ja-Ela', 'Wattala', 'Katunayake'],
    Hambantota: ['Hambantota', 'Tangalle', 'Tissamaharama'],
    Jaffna: ['Jaffna', 'Chavakachcheri', 'Nallur'],
    Kalutara: ['Kalutara', 'Panadura', 'Beruwala'],
    Kandy: ['Kandy', 'Peradeniya', 'Gampola', 'Katugastota'],
    Kegalle: ['Kegalle', 'Mawanella', 'Warakapola'],
    Kilinochchi: ['Kilinochchi', 'Paranthan', 'Karachchi'],
    Kurunegala: ['Kurunegala', 'Wariyapola', 'Maho'],
    Mannar: ['Mannar', 'Nanattan', 'Pesalai'],
    Matale: ['Matale', 'Dambulla', 'Sigiriya'],
    Matara: ['Matara', 'Weligama', 'Dikwella'],
    Monaragala: ['Monaragala', 'Wellawaya', 'Bibile'],
    Mullaitivu: ['Mullaitivu', 'Oddusuddan', 'Puthukudiyiruppu'],
    NuwaraEliya: ['Nuwara Eliya', 'Hatton', 'Talawakelle'],
    Polonnaruwa: ['Polonnaruwa', 'Hingurakgoda', 'Medirigiriya'],
    Puttalam: ['Puttalam', 'Chilaw', 'Wennappuwa'],
    Ratnapura: ['Ratnapura', 'Balangoda', 'Embilipitiya'],
    Trincomalee: ['Trincomalee', 'Kinniya', 'Kantale'],
    Vavuniya: ['Vavuniya', 'Vavunikulam', 'Nedunkeni'],
}

export default DistrictsData
