name: Checks(Eslint+Jest)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - development
    paths:
      - 'backend/**'
      - 'frontend/**'
  push:
    branches:
      - master
      - development
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  Lint-Backend:
    name: Lint backend 
    uses: ./.github/workflows/Eslint-Backend.yml

  Lint-Frontend:
    name: Lint frontend
    uses: ./.github/workflows/Eslint-Frontend.yml

  Lint-Test:
    name: Jest Testing
    uses: ./.github/workflows/Jest.yml